[install]
linker = "hoisted"

[test]
preload = ["./src/shared/infrastructure/test-setup.ts"]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageThreshold = { line = 0.85, function = 0.85, statement = 0.85 }
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "node_modules",
  "dist",
  "src/bin",
  "src/**/__tests__/**",
  "src/**/__integration__/**",
  "src/**/__e2e__/**",
  "src/**/*.test.ts",
  "src/**/*.spec.ts",
]
